### ISSUE TITLE
DataType for expr `(((x > 1) * x) + (x <= 1))` is wrong

### ISSUE THREAD

**Issue by vserret** [Qrlew/qrlew#21]
Related to the propagation of the DataType in the case expressions that contains only one column

**Comment by vserret** [comment]
1 - (x >1) * (1 - x)

**Comment by ngrislain** [comment]
Actually, none of the alternative, including $maximum(x,y) = [a + b + abs(a-b)]/2$ for the same reason.

Let's stick to case or $1 - (x >1) * (1 - x)$.

The real solution is to implement maximum(a,b) which is monotonic everywhere in a and b
