### ISSUE TITLE
create filter_range, filter_values

### ISSUE THREAD

**Issue by vserret** [Qrlew/qrlew#39]
`filter_range`  allows to add min and max to the Schema 
`filter_values` allows to add possible values to the Schema 
Use `limit` for adding the size

**Comment by ngrislain** [comment]
The `filter_xxx` familly of methods on a `Relation` follow the same naming scheme as interval `DataType` builders.

The builders are defined [there](https://github.com/Qrlew/qrlew/blob/3e735377cfc373cc361317abeca0ddc2fb445896/src/data_type/mod.rs#L2546):
```rust
let t = DataType::text();
let iv = DataType::integer_interval(5, 10);
let fv = DataType::float_values(&[5.7, 10.1]);
let ir = DataType::integer_range(0..=5);
```

So the methods would look like:

```rust
impl Map {
    pub fn filter_field(self, name: &str, data_type: DataType) -> Map {
        todo!()
    }

    pub fn filter_interval<B: Bound>(self, name: &str, min: B, max: B) -> Map {
        self.filter_field(name, DataType::from(Intervals::from_interval(min, max)))
    }
    ...
}

impl Relation {
    pub fn identity_filter_field(self, name: &str, data_type: DataType) -> Map {
        todo!()
    }

    pub fn filter_field(self, name: &str, data_type: DataType) -> Map {
        todo!()
    }

    ...
}

```

To be discussed if not clear

**Comment by ngrislain** [comment]
Done and merged
