### ISSUE TITLE
Add a transform that takes a Relation and clips the L2 or L1 norm of all protected entities of a column

### ISSUE THREAD

**Issue by ngrislain** [Qrlew/qrlew#5]
Assume a column defines the protected entity for now

**Comment by vserret** [comment]
1. Find the relation(s) to clip: this can be the innest Relation::Reduce` that is not PEP. When we have joins, We may have several relations to clip.

2. Rescale the columns. Most of the estimators can then be rewritten as sums. 

[clipping_qrlew.pdf](https://github.com/Qrlew/qrlew/files/11598037/clipping_qrlew.pdf)

**Comment by vserret** [comment]
For clipping, we want a primitive that calculates the norm of a column of values according to another column of group by and a column of PEID.

- There is a base of the normed vector space: the groups of the group by.

- A norm for each PEID.

- The coordinates of each PEID on the base: the column of values.
