### ISSUE TITLE
`WHERE` clause ignored for when converting `sqlparser::ast:Query` to `Relation::Reduce`

### ISSUE THREAD

**Issue by vserret** [Qrlew/qrlew#52]
The where clause is ignored when converting `sqlparsed::ast::Query` to `Relation` for queries converted to `Reduce` with a where caluse, i.e. like 'SELECT SUM(b) FROM table WHERE a > 4'

The problem seems to be in `VisitedQueryRelations::try_from_select_items_selection_and_group_by` in sql/relations.rs

**Comment by ngrislain** [comment]
Done

**Comment by ngrislain** [comment]
Closing this issue.
